### PR TITLE
docs: update troubleshooting

### PR DESCRIPTION
**Pull request by wangraying**

### CODE REVIEW

**Review by NOBLES5E — APPROVED** [review]
modified

**Review by NOBLES5E — CHANGES_REQUESTED** [review]
need to fix CI

**Comment by wangraying** [comment]
> modified

not setting  `CUDA_LIBRARY_PATH` environment variable does not necessarily cause failure of MPI/hwloc installations.

**Comment by NOBLES5E** [comment]
wait for @liuhatry finding root cause to see if can be fixed directly in `build.rs`

**Comment by wangraying** [comment]
could not reproduce

**Pull request closed without merging**
